[tools]
bat = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
delta = "latest"
"cargo:sheldon" = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
node = "latest"
starship = "latest"
usage = "latest"
zoxide = "latest"
claude-code = "latest"
gemini-cli = "latest"